services:
  extractlead:
    build: .
    container_name: extractlead
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env
    volumes:
      - ./temp:/app/temp
    restart: unless-stopped
